---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iscsi-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-csi-delete
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: iscsi-test
spec:
  containers:
    - name: iscsi-test
      image: nginx
      volumeMounts:
        - name: data
          mountPath: /data
      ports:
        - containerPort: 80
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: iscsi-test
