{{- if $.Capabilities.APIVersions.Has "snapshot.storage.k8s.io/v1/VolumeSnapshotClass" }}
{{- range $name, $value := $.Values.volumeSnapshotClasses }}
---
{{- with $value | default (dict "isDefault" false) }}
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: {{ default "Delete" .deletionPolicy }}
driver: csi.san.synology.com
kind: VolumeSnapshotClass
metadata:
  labels:
    source: volume-snapshot-class.yaml
    {{- include "synology-csi.labels" $ | nindent 4 }}
  name: {{ printf "%s-%s" (include "synology-csi.fullname" $) $name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ default "false" .isDefault | quote }}
parameters: {{- default dict .parameters | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
